# Generated by Django 5.0.3 on 2024-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
