# Generated by Django 5.0.3 on 2024-04-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees_List',
        ),
    ]
