# Generated by Django 5.0.3 on 2024-04-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('review_date', models.DateTimeField()),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
            ],
        ),
    ]
