# Generated by Django 5.0.3 on 2024-04-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_performancereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_list',
            name='salary',
            field=models.IntegerField(default=11110),
        ),
    ]
