# Generated by Django 5.0.3 on 2024-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
