# Generated by Django 5.0.3 on 2024-04-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_onboarding', '0002_addemployee_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='experience',
            field=models.CharField(max_length=11),
        ),
    ]
